### PR TITLE
Cache serialized

### PR DESCRIPTION
**Pull request by tburmeister**
Idea here is to optionally store the serialized data passed to `ParseFromString` and just return it on a call to `SerializeToString` if the message has not been modified; storage is done recursively on sub messages. I'd like to add this because I have a use case where I am filtering incoming messages and sending back out a subset of the sub messages, so this would save me a lot of serialization time.

### CODE REVIEW

**Comment by grgsrs** [comment]
Why not have the serialize methods also put their results in the cache so that if the message is serialized a second time without being modified, the cached version is used?

**Comment by tburmeister** [comment]
Looks promising!
```In [4]: %timeit t.SerializeToString()
6.28 µs ± 100 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [5]: %timeit t.SerializeToString(True)
167 ns ± 2.88 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)```

**Comment by tburmeister** [comment]
@grgsrs I'm a little confused about how the `_is_present_in_parent` field is used - can you clarify for me? I'm concerned about getting the cache reset semantics correct.

**Comment by grgsrs** [comment]
It's basically a dirty flag that is set to true if any change operations have been applied to the message object (including clearing it). Its can be used as a shortcut to determine if a sub-message is initialized without having to delve into the entire sub-message tree.

**Comment by grgsrs** [comment]
In turns of cache reset semantics, the key issue is that a modification to one message invalidates not only that message's cache, but also the cache of its parent, and its parent and so on.

As it stands pyrobuf only notifies parent messages once when a child message is first modified - thereafter the parent already knows the child was modified and doesn't need to be notified again. However, we likely can't use that optimization if we're caching the serialized message, since the parent must be notified if the child has been modified so it can invalidate its cache.

**Comment by tburmeister** [comment]
Thanks for the clarification, @grgsrs; that all makes sense. I noticed that in most cases we were checking `_is_present_in_parent` _before_ calling `_Modified`, but that the `_Modified` method also checks the `_is_present_in_parent` flag, so I removed the checks before the `_Modified` calls and changed `_Modified` to check _either_ that `_is_present_in_parent` is `False` or that we need to invalidate the cache; I think this both simplifies the code a little and ensure proper cache invalidation - would love to get your thoughts.

**Pull request merged**
